### PR TITLE
Overmodulation implementation + examples

### PR DESCRIPTION
**Pull request by angelicaiaderosa**

### CODE REVIEW

**Comment by lauritapio** [comment]
Hi, Looks good! Perhaps some more detailed comments could be added on some of the the example files.

**Review by mhinkkan — APPROVED** [review]
Well done!

**Comment by mhinkkan** [comment]
@all-contributors please add @angelicaiaderosa for code and examples

**Comment by mhinkkan** [comment]
@all-contributors please add @lauritapio for mentoring

**Pull request merged**
